dt: 0.2
N: 30
Q: [0.5, 0.5, 1.0]
R: [0.5, 0.1]
resolution: 0.05
cost_factor: 0.0
costmap_size: 2.0
inflation_radius: 0.45
reverse_factor: 5.0
rotation_factor: 2.0
look_ahead_distance: 0.5
goal_threshold: 0.1