name: Build ros2_mpc

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  humble-devel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          #- foxy
          # - galactic
          - humble
          # - rolling
        include:
            # Foxy Fitzroy (June 2020 - May 2023)
          # - docker_image: ubuntu:focal
          #   ros_distribution: foxy
          #   ros_version: 2
          #   # Galactic Geochelone (May 2021)
          # - docker_image: ubuntu:focal
          #   ros_distribution: galactic
          #   ros_version: 2
            # Humble Hawksbill (May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
          #   # Rolling
          # - docker_image: ubuntu:jammy
          #   ros_distribution: rolling
          #   ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Install required dependencies
        run: |
            sudo apt-get install -y python3-pip python3-vcstool
            pip3 install -r ros_ws/src/ros2_mpc/requirements.txt    
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: ros2_mpc
          import-token: ${{ secrets.TOKEN_GITHUB }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
  